#spring.application.name=FirstSever
spring:
  application:
    name: FirstSever
  datasource:
    url: jdbc:mariadb://localhost/memo
    username: root
    password: green502



mybatis:
  mapper-locations: mappers/**/*.xml
